import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="legal-page"><div className="legal-shell"><article className="legal-card">
      <h1 className="legal-title">Terms of Use</h1><p className="legal-meta">Effective date: September 17, 2026</p>
      <section className="legal-section"><h2>1. Agreement</h2><p>By accessing or using AlignEDU, you agree to these Terms. If you use the service for an organization, you represent that you are authorized to act for that organization.</p></section>
      <section className="legal-section"><h2>2. Service</h2><p>AlignEDU provides AI-assisted lesson analysis, standards-alignment evidence, instructional insights, dashboards, reporting, and related education tools. Features may evolve over time.</p></section>
      <section className="legal-section"><h2>3. Accounts and Authorized Users</h2><ul><li>Keep credentials secure and account information accurate.</li><li>Individual subscriptions are for the subscribing user and do not include organization user-management rights.</li><li>School and district administrators may invite authorized users subject to their organization plan and permissions.</li></ul></section>
      <section className="legal-section"><h2>4. Subscriptions, Usage and Billing</h2><p>Free and paid plans may include monthly lesson-analysis allowances or other usage limits shown on the pricing page. Paid individual subscriptions renew monthly or annually, depending on the interval selected, until canceled. Annual plans retain the stated monthly analysis allowance unless the plan description says otherwise. School and district plans may use custom pricing, pooled or negotiated usage, and separate order terms. Applicable taxes may be added.</p></section>
      <section className="legal-section"><h2>5. Cancellation and Plan Changes</h2><p>You may cancel a self-service paid subscription through the available billing-management tools. Unless required by law or expressly stated otherwise, cancellation stops future renewal and access to paid features continues through the end of the paid billing period. Plan limits, prices, and features may change prospectively with appropriate notice where required.</p></section>
      <section className="legal-section"><h2>6. Payments and Refunds</h2><p>Payments are processed by third-party payment providers. Except where required by law, fees already paid are generally non-refundable. If a billing error occurs, contact support@alignedu.net so it can be reviewed.</p></section>
      <section className="legal-section"><h2>7. Customer and Education Data</h2><p>You retain ownership of content you are authorized to submit. You grant AlignEDU the limited rights necessary to host, process, secure, analyze, and return that content to provide the service. Schools and districts remain responsible for determining what education records may be submitted and for obtaining permissions or consents required by applicable law and policy.</p></section>
      <section className="legal-section"><h2>8. AI-Assisted Results</h2><p>AlignEDU outputs support professional judgment and may contain errors or incomplete interpretations. They should not be treated as the sole basis for high-stakes employment, disciplinary, grading, special-education, or other consequential decisions.</p></section>
      <section className="legal-section"><h2>9. Acceptable Use and Intellectual Property</h2><p>You must use AlignEDU lawfully and in accordance with the Acceptable Use Policy. AlignEDU software, design, branding, and platform materials remain the property of AlignEDU and its licensors.</p></section>
      <section className="legal-section"><h2>10. Suspension and Termination</h2><p>We may suspend or terminate access for material violations, security threats, nonpayment, or unlawful use. You may stop using the service at any time, subject to subscription cancellation terms.</p></section>
      <section className="legal-section"><h2>11. Disclaimer and Liability</h2><p>The service is provided on an as-available basis. To the maximum extent permitted by law, AlignEDU disclaims implied warranties and liability for indirect, incidental, special, consequential, or punitive damages.</p></section>
      <section className="legal-section"><h2>12. Contact</h2><p>Questions about these terms or billing: support@alignedu.net</p></section>
      <Link href="/pricing" className="legal-back">View Plans</Link> <Link href="/" className="legal-back">Back to Home</Link>
    </article></div></main>
  );
}
